[package]
name = "wasm-crimes-host"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["net", "rt", "rt-multi-thread", "sync", "time", "macros"] }
wasmtime = "36.0.2"
wasmtime-wasi = "36.0.2"
